### ISSUE TITLE
Expression language should be used on query naming

### ISSUE THREAD

**Issue by gehel** [jmxtrans/jmxtrans2#14]
Needs to be re-integrated. This was possible with JMXTrans agent, but has not been ported yet.

**Comment by cyrille-leclerc** [comment]
FYI: Expression language is also available in embedded-jmxtrans thanks to [ResultNameStrategy.java](https://github.com/jmxtrans/embedded-jmxtrans/blob/master/src/main/java/org/jmxtrans/embedded/ResultNameStrategy.java).

**Comment by gehel** [comment]
This seems to be already the case in JmxTrans2. There is still some clean up required (there are 2 implementation of this at the moment) and better integration testing is needed.

**Comment by gehel** [comment]
Cleanup done as part of #18. Additional improvements are probably needed, but are out of scope for this specific issue.
