### ISSUE TITLE
Query type should be an enum

### ISSUE THREAD

**Issue by gehel** [jmxtrans/jmxtrans2#70]
At the moment, the type of a query (and of its result) is a free form string, which is expected to be `counter`, `gauge`, ... This is an obvious candidate for an enum.

**Comment by cyrille-leclerc** [comment]
Shouldn't we prepare for extension?

For example, Prometheus supports the following metric types: Summary, Gauge, Counter, Untyped. "Summary" was new to me.

See [Prometheus Client Data Exposition Format](https://docs.google.com/document/d/1ZjyKiKxZV83VI9ZKAXRGKaUKK2BIWCT7oiGBKDBpjEY/edit#)

**Comment by gehel** [comment]
There is impedance mismatch between the configuration format where the type is defined and the output format managed by the different OutputWriters. So conversion is needed anyway. It does work as-is for a few OutputWriter, but this is accidental. Enum will allow to give us warnings where th code does not support correct output.
