### ISSUE TITLE
Time- related tests failure

### ISSUE THREAD

**Issue by vchekan** [jmxtrans/jmxtrans2#75]
2 tests are failing for me: logLineContainsAllRequiredInformation and logLineContainsException:

java.lang.AssertionError: 
Expecting:
 "1969.12.31 16:16:40.000 - DEBUG - testLogger - testMessage
"
to match pattern:
 ".*1970\.01\.01 ..:16:40\.000.*"
	at org.jmxtrans.core.log.PrintWriterLoggerTest.logLineContainsAllRequiredInformation(PrintWriterLoggerTest.java:122)

Seems it is related to me being in UTC+7 timezone.

**Comment by gehel** [comment]
Damn, time is always more complex than I think it is ...
